### ISSUE TITLE
Option to hide task bar 

### ISSUE THREAD

**Issue by extreemator** [pijulius/xposeddex#1]
Please add option to hide low task bar. Also if possible to block swiftkey turning on screen.

**Comment by pijulius** [comment]
You can easily hide taskbar all together by simply running:
settings put global policy_control immersive.full=*

from adb shell. You can revert this change by running:
settings delete global policy_control

Re swiftkey, not sure what it is, tried to google around swiftkey and galaxy tab s6, but seems like some kind of keyboard so sorry but can't do much in there as this module is all about dex and original samsung apps.

**Comment by extreemator** [comment]
I ran it in terminal and it didn't work but now in dex home button doesn't work and double click on it turns off screen and it didn't launch immersive status bar. Woot. Reset line doesn't do anything. That's on tab s6. Btw your extension works on android 9.
I have dex on s9 but don't want to try yet coz seems i'll just break home button.

Could you please debug it and add inside the module though like you did for top bar? , i use it for reading or watching, and readers don't support immersive.

Look another small suggestion: can you return home button to middle button of mouse, they removed but without giving middle button it's default function (thx samsung asl always great job) 

And very important - to add in the module adjustable DPI. Bigger dpi. I turn on it to TV and can't see a dime of text. 

Sorry I just thought that everyone knows what is swiftkey, very popular keyboard, stock is good for proprietary functionality but more akward but i agree they should fix but likely won't. But yea we can focus on fixing sung's crap, it's way more than enough ;(
